### PR TITLE
Make SnappyOutputStream.close() idempotent; guard against writing to closed stream

### LINKED ISSUE #107: SnappyOutputStream.close() is not idempotent
SnappyOutputStream's `close()` method is not idempotent, which can lead to stream corruption issues when CachedBufferAllocator is used (the default behavior).

Here's the current source for `close()`:

```java
    public void close() throws IOException {
        try {
            flush();
            out.close();
        } finally {
            inputBufferAllocator.release(inputBuffer);
            outputBufferAllocator.release(outputBuffer);
        }
    }
```

If we call close() twice, then we'll free the buffers twice.  After the first close() call, the stream's buffers will be released back to the BachedBufferAllocator's buffer pool for re-use.  If we create a new SnappyOutputStream, this stream will re-use the buffers from the BachedBufferAllocator.  If we now call close() on the original stream a second time, we'll end up placing the same buffers into the BachedBufferAllocator's buffer pool even though another non-closed SnappyOutputStream is now using them.  This can lead to scenarios where two open SnappyOutputStreams share the same buffers, leading to stream corruption issues.

This should be pretty easy to fix; I'm working on a unit test + patch now.

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch will fix #107, an issue where `SnappyOutputStream.close()` is not idempotent.

The first commit is a failing regression test which shows how a non-idempotent `close()` can lead to stream corruption issues.

### CODE REVIEW

**Comment by JoshRosen** [comment]
Here's a failing run of the regression test: https://travis-ci.org/xerial/snappy-java/jobs/62514893

**Comment by JoshRosen** [comment]
Even though this patch makes `close()` idempotent, I suppose there's still the potential for stream corruption if a user continues to call `write()` methods on a SnappyOutputStream after calling `close()` on it.  Do you think that we should also add a `!closed` check in `rawWrite()` to guard against this case?  Alternatively, I guess that we could null out the references to the buffers to be absolutely sure that we can't access them after `close()`.

**Comment by xerial** [comment]
Thanks for the fix. 

I think checking `!close` has negligible overhead. 
And also nulling out the buffers is also good for GC. 

Please add both.

**Comment by JoshRosen** [comment]
I've updated this patch to include nulling of output buffers and `if(closed)` checks.

File: src/test/java/org/xerial/snappy/SnappyOutputStreamTest.java [hunk 1]
```diff
@@ -158,6 +163,83 @@ public void batchingOfWritesShouldNotAffectCompressedDataSize() throws Exception
...
+    }
+
+    @Test
+    public void closingStreamShouldMakeBuffersEligibleForGarbageCollection() throws IOException {
+        ByteArrayOutputStream b = new ByteArrayOutputStream();
+        SnappyOutputStream os = new SnappyOutputStream(b, 4095, DefaultBufferAllocator.factory);
+        WeakReference<byte[]> inputBuffer = new WeakReference<byte[]>(os.inputBuffer);
+        WeakReference<byte[]> outputBuffer = new WeakReference<byte[]>(os.inputBuffer);
+        os.close();
+        System.gc();
```
Comment (xerial) [inline src/test/java/org/xerial/snappy/SnappyOutputStreamTest.java]: Is this necessary?

Comment (JoshRosen) [inline src/test/java/org/xerial/snappy/SnappyOutputStreamTest.java]: The goal here was to test that the now weakly-referencable buffers get reclaimed by GC.

**Comment by xerial** [comment]
Looks good! Thank you for the improvements.
